# Generated by Django 5.2.10 on 2026-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_color_class',
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(default='primary', max_length=50),
        ),
    ]
